import { TokenDisabled,
UserPerson,
Binnacle,
Module,
Privilege,
Role,
User,
Session,
SessionType,
Permission,
RolePermission } from './../../../../shared/domain/model/aaa';
export const connectionProvider = [
{ provide: 'TokenDisabledRepository', useValue: TokenDisabled },
{ provide: 'UserPersonRepository', useValue: UserPerson },
{ provide: 'BinnacleRepository', useValue: Binnacle },
{ provide: 'ModuleRepository', useValue: Module },
{ provide: 'PrivilegeRepository', useValue: Privilege },
{ provide: 'RoleRepository', useValue: Role },
{ provide: 'UserRepository', useValue: User },
{ provide: 'SessionRepository', useValue: Session },
{ provide: 'SessionTypeRepository', useValue: SessionType },
{ provide: 'PermissionRepository', useValue: Permission },
{ provide: 'RolePermissionRepository', useValue: RolePermission }];export const models = [
TokenDisabled,
UserPerson,
Binnacle,
Module,
Privilege,
Role,
User,
Session,
SessionType,
Permission,
RolePermission];