import { ChargeStatus,
ChargeDetailScheduled,
MeasureUnit,
Charge,
Product,
ChargeDetail,
DischargeStatus,
DischargeDetailScheduled,
Discharge,
DischargeDetail,
Warehouse,
WarehouseEvent,
Binnacle,
Event,
InventoryMovement,
Measure,
PriceCategory,
ProductMaintenanceStep,
ProductType,
Vehicle,
ProductMaintenanceStepDetail,
ProductPrice,
WarehouseAddress,
WarehouseType,
WarehouseVehicle } from './../../../../shared/domain/model/inventory';
export const connectionProvider = [
{ provide: 'ChargeStatusRepository', useValue: ChargeStatus },
{ provide: 'ChargeDetailScheduledRepository', useValue: ChargeDetailScheduled },
{ provide: 'MeasureUnitRepository', useValue: MeasureUnit },
{ provide: 'ChargeRepository', useValue: Charge },
{ provide: 'ProductRepository', useValue: Product },
{ provide: 'ChargeDetailRepository', useValue: ChargeDetail },
{ provide: 'DischargeStatusRepository', useValue: DischargeStatus },
{ provide: 'DischargeDetailScheduledRepository', useValue: DischargeDetailScheduled },
{ provide: 'DischargeRepository', useValue: Discharge },
{ provide: 'DischargeDetailRepository', useValue: DischargeDetail },
{ provide: 'WarehouseRepository', useValue: Warehouse },
{ provide: 'WarehouseEventRepository', useValue: WarehouseEvent },
{ provide: 'BinnacleRepository', useValue: Binnacle },
{ provide: 'EventRepository', useValue: Event },
{ provide: 'InventoryMovementRepository', useValue: InventoryMovement },
{ provide: 'MeasureRepository', useValue: Measure },
{ provide: 'PriceCategoryRepository', useValue: PriceCategory },
{ provide: 'ProductMaintenanceStepRepository', useValue: ProductMaintenanceStep },
{ provide: 'ProductTypeRepository', useValue: ProductType },
{ provide: 'VehicleRepository', useValue: Vehicle },
{ provide: 'ProductMaintenanceStepDetailRepository', useValue: ProductMaintenanceStepDetail },
{ provide: 'ProductPriceRepository', useValue: ProductPrice },
{ provide: 'WarehouseAddressRepository', useValue: WarehouseAddress },
{ provide: 'WarehouseTypeRepository', useValue: WarehouseType },
{ provide: 'WarehouseVehicleRepository', useValue: WarehouseVehicle }];export const models = [
ChargeStatus,
ChargeDetailScheduled,
MeasureUnit,
Charge,
Product,
ChargeDetail,
DischargeStatus,
DischargeDetailScheduled,
Discharge,
DischargeDetail,
Warehouse,
WarehouseEvent,
Binnacle,
Event,
InventoryMovement,
Measure,
PriceCategory,
ProductMaintenanceStep,
ProductType,
Vehicle,
ProductMaintenanceStepDetail,
ProductPrice,
WarehouseAddress,
WarehouseType,
WarehouseVehicle];