import { ChargeStatus,
ChargeDetailScheduled,
MeasureUnit,
Charge,
Product,
ChargeDetail,
DischargeStatus,
DischargeDetailScheduled,
Discharge,
DischargeDetail,
Binnacle,
InventoryMovement,
Measure,
PriceCategory,
ProductMaintenanceStep,
ProductMaintenanceStepDetail,
ProductPrice,
ProductType } from './../../../../shared/domain/model/inventory';
export const connectionProvider = [
{ provide: 'ChargeStatusRepository', useValue: ChargeStatus },
{ provide: 'ChargeDetailScheduledRepository', useValue: ChargeDetailScheduled },
{ provide: 'MeasureUnitRepository', useValue: MeasureUnit },
{ provide: 'ChargeRepository', useValue: Charge },
{ provide: 'ProductRepository', useValue: Product },
{ provide: 'ChargeDetailRepository', useValue: ChargeDetail },
{ provide: 'DischargeStatusRepository', useValue: DischargeStatus },
{ provide: 'DischargeDetailScheduledRepository', useValue: DischargeDetailScheduled },
{ provide: 'DischargeRepository', useValue: Discharge },
{ provide: 'DischargeDetailRepository', useValue: DischargeDetail },
{ provide: 'BinnacleRepository', useValue: Binnacle },
{ provide: 'InventoryMovementRepository', useValue: InventoryMovement },
{ provide: 'MeasureRepository', useValue: Measure },
{ provide: 'PriceCategoryRepository', useValue: PriceCategory },
{ provide: 'ProductMaintenanceStepRepository', useValue: ProductMaintenanceStep },
{ provide: 'ProductMaintenanceStepDetailRepository', useValue: ProductMaintenanceStepDetail },
{ provide: 'ProductPriceRepository', useValue: ProductPrice },
{ provide: 'ProductTypeRepository', useValue: ProductType }];export const models = [
ChargeStatus,
ChargeDetailScheduled,
MeasureUnit,
Charge,
Product,
ChargeDetail,
DischargeStatus,
DischargeDetailScheduled,
Discharge,
DischargeDetail,
Binnacle,
InventoryMovement,
Measure,
PriceCategory,
ProductMaintenanceStep,
ProductMaintenanceStepDetail,
ProductPrice,
ProductType];