import { Quotation,
Binnacle,
Client,
Maintenance,
MaintenanceStatus,
MaintenanceStep,
MaintenanceStepDetail,
QuotationCharge,
QuotationDetail,
QuotationMaintenance,
QuotationStatus,
Supplier } from './../../../../shared/domain/model/billing';
export const connectionProvider = [
{ provide: 'QuotationRepository', useValue: Quotation },
{ provide: 'BinnacleRepository', useValue: Binnacle },
{ provide: 'ClientRepository', useValue: Client },
{ provide: 'MaintenanceRepository', useValue: Maintenance },
{ provide: 'MaintenanceStatusRepository', useValue: MaintenanceStatus },
{ provide: 'MaintenanceStepRepository', useValue: MaintenanceStep },
{ provide: 'MaintenanceStepDetailRepository', useValue: MaintenanceStepDetail },
{ provide: 'QuotationChargeRepository', useValue: QuotationCharge },
{ provide: 'QuotationDetailRepository', useValue: QuotationDetail },
{ provide: 'QuotationMaintenanceRepository', useValue: QuotationMaintenance },
{ provide: 'QuotationStatusRepository', useValue: QuotationStatus },
{ provide: 'SupplierRepository', useValue: Supplier }];export const models = [
Quotation,
Binnacle,
Client,
Maintenance,
MaintenanceStatus,
MaintenanceStep,
MaintenanceStepDetail,
QuotationCharge,
QuotationDetail,
QuotationMaintenance,
QuotationStatus,
Supplier];